### ISSUE TITLE
你好，请问你使用的是哪个版本的chinese-bert-wwm-ext

### ISSUE THREAD

**Issue by zhongtao93** [taishan1994/pytorch_bert_intent_classification_and_slot_filling#1]
如题，我使用的是 hfl/chinese-bert-wwm-ext, 意图识别准确率96%，槽填充只有91%
<img width="336" alt="image" src="https://user-images.githubusercontent.com/15263824/226794440-48bf2cf7-c3a1-4415-b3ef-cadafeb8e55d.png">

**Comment by zhongtao93** [comment]
另外这个效果是正常的么
<img width="352" alt="image" src="https://user-images.githubusercontent.com/15263824/226796105-00914905-1a6a-4cd9-b182-bbc69dcb545c.png">

**Comment by taishan1994** [comment]
> 如题

就是hfl的。 效果正常，因为有类别的数据量很少，所以识别的效果可能不太好。

**Comment by zhongtao93** [comment]
我理解这个实现应该是和jointBert差不多吧
现在还有效果更好的方法或思路吗，感觉大家在2020后都停滞这块的研究

**Comment by taishan1994** [comment]
> 我理解这个实现应该是和jointBert差不多吧 现在还有效果更好的方法或思路吗，感觉大家在2020后都停滞这块的研究

是和jointbert差不多，具体研究没有了解了，可以去查下相关的论文看看。
